name: launch-ubuntu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Chrome Remote Desktop authorization code'
        required: true
      pincode:
        description: '6-digit pincode'
        required: true

jobs:
  ubuntu-remote-access:
    runs-on: ubuntu-latest

    steps:
    - name: Update and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget desktop-base xscreensaver
        sudo apt-get install -y xfce4 xfce4-goodies  # Install Xfce desktop environment

    - name: Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
        sudo apt-get install -f  # Fix any dependency issues

    - name: Configure Chrome Remote Desktop Session
      env:
        AUTHCODE: ${{ github.event.inputs.authcode }}
        PINCODE: ${{ github.event.inputs.pincode }}
      run: |
        # Configure Xfce as the default desktop environment for CRD
        sudo bash -c 'echo "exec /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        
        # Add the current user to the CRD group
        sudo usermod -a -G chrome-remote-desktop $USER

        # Authenticate and set up Chrome Remote Desktop
        # This command uses the AUTHCODE and PINCODE for initial setup
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="$AUTHCODE" --redirect-url="https://remotedesktop.google.com/" --name="GitHub Ubuntu Remote Access" --pin="$PINCODE"

    - name: Keep Session Active
      run: |
        while true; do
          echo "Session is active"; sleep 3600
        done
