name: launch-ubuntu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Link'
        required: true
      pincode:
        description: '6-digit pincode'
        required: true

jobs:
  ubuntu-remote-access:
    runs-on: ubuntu-latest

    steps:
    - name: Install Chrome Remote Desktop
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt install ./chrome-remote-desktop_current_amd64.deb -y
        
    - name: Configure Chrome Remote Desktop
      run: |
        echo "${{ github.event.inputs.authcode }}" -pin=111111

    - name: Keep Session Active
      run: |
        while true; do
          echo "Session is active"; sleep 3600
        done
