name: launch-ubuntu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Chrome Remote Desktop authorization code'
        required: true
      pincode:
        description: '6-digit pincode'
        required: true

jobs:
  ubuntu-remote-access:
    runs-on: ubuntu-latest

    steps:
    - name: Install Chrome Remote Desktop
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt install -y ./chrome-remote-desktop_current_amd64.deb

    - name: Configure Chrome Remote Desktop
      env:
        AUTHCODE: ${{ github.event.inputs.authcode }}
        PINCODE: ${{ github.event.inputs.pincode }}
      run: |
        # Registering the host with the auth code and setting the PIN
        sudo /opt/google/chrome-remote-desktop/start-host --code="$AUTHCODE" --pin="$PINCODE"

    - name: Keep Session Active
      run: |
        while true; do
          echo "Session is active"; sleep 3600
        done
