name: Launch Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh
          echo "AllowTcpForwarding yes" | sudo tee -a /etc/ssh/sshd_config
          echo "GatewayPorts yes" | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart sshd

      - name: Add public SSH key from GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          echo "SSH public key added"

      - name: Output SSH connection details
        run: |
          echo "SSH server is running. To connect, use your private key."

      - name: Prevent timeout (Keep machine alive)
        run: |
          echo "Runner will stay alive for the next 1 hour..."
          sleep 14400
