name: launch-windows

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CRD link'
        required: true
      pincode:
        description: '6-digit pincode'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup the CRD
      run: ./setup.ps1
    - name: Specify data for CRD.
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Install the required software
      run: ./download.ps1
    - name: Timeout script
      run: ./timeout.ps1
      env:
        ARGS: "-av"
